name: sirius_tracker_contratante
description: Aplicativo para cadastro de serviços

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^5.1.4+2
  provider: ^2.0.1+1
  animator: ^1.0.0+1
  splashscreen: ^1.2.0
  cupertino_icons: ^0.1.2
  location: ^2.3.5
  google_maps_flutter: ^0.4.0
  font_awesome_flutter: ^8.2.0
  http: ^0.12.0+2
  url_launcher: ^5.0.3
  flutter_swiper : ^1.1.6
  firebase_auth: ^0.14.0+5
  #  flutter_facebook_login: ^1.1.1
  shared_preferences: ^0.5.3+4
  cloud_firestore: ^0.12.9+5
  firebase_core: ^0.4.0
  google_sign_in: ^4.0.7
  flutter_launcher_icons: ^0.7.3
  firebase_storage: 3.0.4
  image_cropper: 1.0.2
  image_picker: 0.6.0+17
  flutter_money_formatter: ^0.8.3
  intl: ^0.15.7
  cached_network_image: ^2.0.0-rc
  flutter_masked_text: ^0.8.0
  toast: ^0.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/default.png
    - assets/images/google_logo.png
    - assets/images/facebook_logo.png
    - assets/images/mylocation.png
    - assets/images/cnh.png
    - assets/images/img_not_available.jpeg
    - assets/images/card.png
    - assets/images/contact.png
    - assets/images/configuration.png
    - assets/images/information.png
    - assets/images/notes.png
    - assets/images/conversation.png
    - assets/images/nodata.png
    - assets/images/profile.png
    - assets/icon/app.gif


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

module:
    androidX: true